# 项目相关配置
ruoyi:
  # 名称
  name: his
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: false
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: E:/his-service/uploadPath/
  # 获取ip地址开关
  addressEnabled: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: info
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）KeyGenerator keygen = KeyGenerator.getInstance("AES"); SecretKey deskey = keygen.generateKey(); System.out.println(Base64.encodeToString(deskey.getEncoded()));
    cipherKey: zSyK5Kp6PZAAjlT+eeNMlg==
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 300
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 10
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 30
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

redis:
  host: 127.0.01
  jedis:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
  password: ''
  port: 6379
  timeout: 10000


his:
  service:
#    name: xuwen
    name: nongken
    #农垦中心医院-外网
#    url: http://app.gdsnkzxyy.cn:8031/ou/hiswx.asmx
    #农垦中心医院-内网
    url: http://192.168.0.59:8031/Ou/hiswx.asmx
  wechat:
    #AppID
    appId: wx50617d578b93801d
    #appSecret
    appsecret: d2258bd67e9ef6bb8a795c723f483301
    #商户号
    mchid: 1433629902
    #key值
    key: A44de8673b0f2d1603a6ff33b18b81EF
    #回调地址
    baseUrl: http://app.gdsnkzxyy.cn/his/wechat/notify_weixin
    #退款地址
    refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
    #支付地址
    unifiedorderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
    #退款证书
    refundCert: E:\his-service\apiclient_cert.p12
  wxapp:
    #AppID
    appId: wx50617d578b93801d
    #appSecret
    appsecret: d2258bd67e9ef6bb8a795c723f483301
    #商户号
    mchid: 1433629902
    #key值
    key: A44de8673b0f2d1603a6ff33b18b81EF
    #回调地址
    baseUrl: http://app.gdsnkzxyy.cn/his/wechat/notify_weixin
    #退款地址
    refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
    #支付地址
    unifiedorderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  aliapp:
    #应用Id
    appid: 2017031306201007
    #合作身份者ID
    partner: 2088521631668130
    #商户的支付宝账号
    seller_account: gdsnkzxyy@qq.com
    #商户的私钥
    private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8W3wCnCCyp1lpNqGB/EQFy2zC9+ZWW+nyelV7pG+ryDxL9fZj0pOdnqSZUG3J0K6genPmwLoMJYGdTdMOHaL6yQJni25ptfu7DbitroHLhLW5cR3UaXd7GA2IAdopj64DqQ0hiCCWSOmBR5MVoLY+sgw2Pr2bo8l0D7rr1a+YkRzYHUL69X9L9fqEdBu2Qxgm0FILZJc3BEKB5L3prf6XCkgYh5S4KtuNbqQcH3uOGgMZZbVgfSXTxjTqe0oua3PFt+MiLRwwYG0AnhorT8yuBwMyU9JCXb5YauWteC5QAwQ8vRZ8dUE8Fihn0f4MfA7gqtQ8Z4C4M/S8lDPtg6aDAgMBAAECggEAXb+/AmGJGMKYiviI/HR9utCcKpJOT89hqrFe2LJobny0Hi6m2tpVZI8wZ6qTam52bCNmioSEVUVZtNymXpE7rEzd6IGKjAzq5RgYQkHoEk7UUB9P9Igl0tuO6JHbbvI3b1T11ym05ngV2KWyPIKIEr51u44Qu2WTADRQGc96nZlJtLOn7vznT460nCLkhWEsfwI77vrt0lm1tq/jNpyQHrvjonnPzOeJtbrSC/d3XRzFjDBixR0hRROW3yN+dQ5vUJ612EYnJWdaXDZTCXG5UDKlp++QEZfI/dZiE4hdMvhN35pnUF5i1wfqSrj4lunbAp20WJFU0339MMgvcQSESQKBgQDhEo9hrTgRieJsYtPLFgJAz1NECgVcFJZHYiAO8ULnK9iUlKGI96/pl8d8KIjYZkXC03sboEHQ7RK9S0jyVq9JzcWkkNVZSnzaRXAf1WMMM0tTzcIT24wDusvYnS9zi95sFZqAn1c/61Bip5rGS5ZNs5CEmNv5nU7+8JRutyfMJQKBgQDWPWKltRQL/ViEEjtj1A/CdM+6W5KBN3NjSjroyrpaOFyCnD18/NyOWyxFWj0aRVRSCKtwTv22Z8oD+R5JTbW1toIFAF0AKBWheTXQ9jnUsGpA5MaL26wLlJ/UJDEFtLWfSaAuOu/RIdmkO+yyYeBA7N4bonbqUr5XeinBo8tThwKBgFN9phCOyCjBZGvecUB5xpYyEmo/6WMSA/kw7kF8v9uvSSU8yXtcnjXh5s8o3jKgJaqy9oz18tREzVnI7qNvApE3MuTsESiRWCVD8ubsKlThRkUtI5xoKdVMWsfc7zhGn1iq3uhts1jzupsOH30Flxj1zltRtPAwqZgquHUlni69AoGBAI5jK/4gNFunnL3idDBsD7FY+3rLQ7q3xOvXuQFhQ6uUy/9OohtA38GJXQoW6IdeTqVa975j8YHax0wOtQ9ZI4zK6O00CZuCCKZSLe9cxqDSQzwwELmBXX4w4G0ZRK+bJB7iyyAOsbbX/ZOG9FC2dloQU6ogN1KTfcgb/Eajew5fAoGAGkAYnW9u2SMpFmQYuoF6bSXZaiRzppfI27zh0btK7vGJdem3Mdgt4GA0qX9OFuGlF8UtUbJptDgh9k3MSxBsqJH1EwJumPMLiVTRjliYUn3O8DGXsqrSfwLXKWEBQakJ10kwJAQFUKcQEVWoiFEk46iNzni4ZLGSF6D57migt24=
    #支付宝的公钥
    ali_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi1bw+zczwfg8/WpCkg8L9LHvMWvQ5Y+I8JP9O5vHV9gBY8EZ/1ahWPHqbPPXi4NlTZSc7co5fbtERM7x2gvCc+hXN9TXKM66MeNFpHcu/bMbEezKWrEFHpBffHSb82XR6ldnr14v1tDf2Q59kth2U/7LENaiLr3Y7aDSBuOIW7TSacMfpSbAit+ibfz1XRMiOVQlLK/Gpcu20w4kDS7UMYEkkhQIA0Nd/FwRoNgIVm/PySwCjI8UZCX3OuX1xUjo8dzkTJ1uK7888AEbF1SwFNNKSN1NzyRpzmBborpCDPxqEjog3sjjR2b87qY3uLwID9Cb06GA1ie42L9/GBdhYQIDAQAB
    #回调地址
    baseUrl: http://app.gdsnkzxyy.cn/his/wechat/notify_alipay
    #退款地址
    refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
  healthcard:
    appId: 786f063eed41c3e6da9f636bf48b3b1a
    appSecret: fd4dd78ccd2210e2f9aa231a7b874699
    hospitalId: 31676
    channelNum: 0